@protocol = http
@hostname = localhost
@port = 3000
@baseUrl = {{protocol}}://{{hostname}}:{{port}}
###
GET {{baseUrl}}/api/test
###
###
###   AUTH
###
###
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "test@foo.com",
    "password": "Pas2w0rd"
}
###
###
###   PREPARATION
###
###
###
POST {{baseUrl}}/api/sermons/speaker
Content-Type: application/json

{
    "initials": "MM",
    "name": "Max Mustermann"
}
###
###
###   SERMONS UPLOAD
###
###
@fileName = tvari-tokyo-cafe-159065.mp3
@audioFileId = 651de1a14e278e8f1b8dd210
@sermonTitle = Tvari Tokyo Cafe
### File upload - Change path, filename and filetype to upload different file.
POST {{baseUrl}}/api/files?fileName={{fileName}}
Content-Type: audio/mpeg

< ./test-files/{{fileName}}
###
POST {{baseUrl}}/api/sermons/
Content-Type: application/json

{
    "audioFileId": "{{audioFileId}}",
    "date": 1696364323231,
    "speaker": "651c8a11d6cc86b3e3bf8e4e",
    "title": "{{sermonTitle}}"
}
###
###
###   LIST STUFF
###
###
### Get sermons list
GET {{baseUrl}}/api/sermons
