FROM node:lts

WORKDIR /app

RUN npm install -g pnpm

ENV POSTGRES_URL="${POSTGRES_URL}"

ENV MAILING_HOST="${MAILING_HOST}"
ENV MAILING_PORT="${MAILING_PORT}"
ENV MAILING_USER="${MAILING_USER}"
ENV MAILING_PASSWORD="${MAILING_PASSWORD}"
ENV MAILING_FROM_MAIL_ADDRESS="${MAILING_FROM_MAIL_ADDRESS}"
ENV MAILING_CONTACT_TO_MAIL_ADDRESS="${MAILING_CONTACT_TO_MAIL_ADDRESS}"

ENV GDF_JWT_SIGNING_SECRET="${GDF_JWT_SIGNING_SECRET}"

ENV GDF_WEB_HOSTNAME="${GDF_WEB_HOSTNAME}"
ENV GDF_JSON_LOG="${GDF_JSON_LOG}"

ENV NEXT_PUBLIC_GDF_FEATURE_FLAGS="${NEXT_PUBLIC_GDF_FEATURE_FLAGS}"
ENV NEXT_PUBLIC_GDF_DEV_FEATURE_FLAGS="${NEXT_PUBLIC_GDF_DEV_FEATURE_FLAGS}"

ENV GDF_DEV_DATABASE_REPLACE_EXISTING_DATA="0"
ENV GDF_PROD_DATABASE_REPLACE_EXISTING_DATA="0"
ENV GDF_PROD_DATABASE_REPLACE_EXISTING_DATA_TOKEN=""

COPY . .

RUN pnpm i --frozen-lockfile
RUN pnpx update-browserslist-db@latest

ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

CMD [ "npm", "run", "ci:start" ]
