version: "2"

services:
  mongodb:
    image: prismagraphql/mongo-single-replica:5.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
  web:
    build: .
    restart: "unless-stopped"
    ports:
      - 3000:3000
    environment:
      MONGODB_URL: mongodb://admin:admin@localhost:27017/prisma-test?authSource=admin&directConnection=true
    depends_on:
      - mongodb
