FROM node:lts

WORKDIR /app

RUN npm install -g pnpm

ENV POSTGRES_URL="${POSTGRES_URL:-postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-gemeinde-der-fels-de}?schema=public}"
ENV GDF_DEV_DATABASE_REPLACE_EXISTING_DATA="0"
ENV GDF_FILES_FOLDER="${GDF_FILES_FOLDER:-./test-files}"
ENV GDF_JWT_SIGNING_SECRET="${GDF_JWT_SIGNING_SECRET}"
ENV NEXT_PUBLIC_GDF_FEATURE_FLAGS="${NEXT_PUBLIC_GDF_FEATURE_FLAGS}"
ENV NEXT_PUBLIC_GDF_DEV_FEATURE_FLAGS="${NEXT_PUBLIC_GDF_DEV_FEATURE_FLAGS}"

COPY . .

RUN pnpm i --frozen-lockfile

ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

CMD [ "npm", "run", "ci:start" ]
