name: gdf-website-services

services:
    db:
        image: postgres:latest
        container_name: GDF-DB
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_PORT: "${POSTGRES_PORT}"
            POSTGRES_DB: "${POSTGRES_DB}"

        restart: always
        healthcheck:
            test:
                ["CMD-SHELL", "pg_isready -U postgres -d gemeinde-der-fels-de"]
            interval: 10s
            timeout: 10s
            retries: 10

    web:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: GDF-Web
        ports:
            - "${GDF_WEB_EXPOSE_PORT}:3000"
        environment:
            POSTGRES_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}"

            MAILING_HOST: "${MAILING_HOST}"
            MAILING_PORT: "${MAILING_PORT}"
            MAILING_USER: "${MAILING_USER}"
            MAILING_PASSWORD: "${MAILING_PASSWORD}"
            MAILING_FROM_MAIL_ADDRESS: "${MAILING_FROM_MAIL_ADDRESS}"

            GDF_JWT_SIGNING_SECRET: "${GDF_JWT_SIGNING_SECRET}"

            GDF_WEB_EXPOSE_PORT: "${GDF_WEB_EXPOSE_PORT}"
            GDF_WEB_HOSTNAME: "${GDF_WEB_HOSTNAME}"
            GDF_JSON_LOG: "${GDF_JSON_LOG}"

            NEXT_PUBLIC_GDF_FEATURE_FLAGS: "${NEXT_PUBLIC_GDF_FEATURE_FLAGS}"
            NEXT_PUBLIC_GDF_DEV_FEATURE_FLAGS: "${NEXT_PUBLIC_GDF_DEV_FEATURE_FLAGS}"

            GDF_DEV_DATABASE_REPLACE_EXISTING_DATA: "${GDF_DEV_DATABASE_REPLACE_EXISTING_DATA}"
            GDF_PROD_DATABASE_REPLACE_EXISTING_DATA: "${GDF_PROD_DATABASE_REPLACE_EXISTING_DATA}"
            GDF_PROD_DATABASE_REPLACE_EXISTING_DATA_TOKEN: "${GDF_PROD_DATABASE_REPLACE_EXISTING_DATA_TOKEN}"

        depends_on:
            db:
                condition: service_healthy
                required: true
                restart: true

        restart: "on-failure"
        healthcheck:
            test:
                ["CMD", "curl", "-f", "http://localhost:${GDF_WEB_EXPOSE_PORT}"]
            interval: 10s
            timeout: 10s
            retries: 10
