version: "2"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  web:
    build: .
    restart: "unless-stopped"
    ports:
      - 3000:3000
    environment:
      MONGODB_URL: mongodb://admin:admin@localhost:27017/prisma-test?authSource=admin&directConnection=true
    depends_on:
      - mongodb
