export const returnToPathParamName = "returnTo"
export const resetPasswordTokenParamName = "token"
export const fileNameParamName = "fileName"
export const requiresUserFlagParamName = "requiresUserFlag"
export const fileRoleParamName = "role"
export const pageSizeParamName = "pageSize"
export const afterIdParamName = "afterId"
export const showDisabledParamName = "showDisabled"
